_target_: nablaDFT.optimization.SpkBatchwiseCalculator
device: ${device}
atoms_converter:
  _target_: schnetpack.interfaces.ase_interface.AtomsConverter
  device: ${device}
  neighbor_list:
    _target_: schnetpack.transform.ASENeighborList
    cutoff: 5.0
energy_unit: Hartree
position_unit: Ang
