repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0  # Use the ref you want to point at
    hooks:
      - id: check-docstring-first
        exclude: ^nablaDFT/phisnet
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.9
    hooks:
      # Run linter
      - id: ruff
        types_or: [ python, pyi, jupyter ]
      # Sort imports
      - id: ruff
        types_or: [ python, pyi, jupyter ]
        args: [ "check", "--select", "I", "--fix" ]
      # Run the formatter.
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]