_target_: pytorch_lightning.Trainer

deterministic: True
accelerator: "gpu"
devices: [0]
strategy:
  _target_: pytorch_lightning.strategies.ddp.DDPStrategy
  # QHNet has unused params, uncomment line for train
  # find_unused_parameters: True
max_steps: ${max_steps}

# example of additional arguments for trainer
# gradient_clip_algorithm: norm
# gradient_clip_val: 5.0

log_every_n_steps: 10
