_target_: pytorch_lightning.Trainer

deterministic: True
devices: ${devices}
max_steps: ${max_steps}

gradient_clip_algorithm: ${gradient_clip_algorithm}
gradient_clip_val: ${gradient_clip_val}

log_every_n_steps: 10
