# Dataset config for torch geometric nablaDFT
_target_: nablaDFT.dataset.PyGHamiltonianDataModule

root: ./datasets/nablaDFT/hamiltonian
dataset_name: ${dataset_name}
seed: 23
# Dataloader args
batch_size: 2
num_workers: 4
persistent_workers: True
pin_memory: True