# Dataset config for torch geometric nablaDFT
_target_: nablaDFT.dataset.NablaDFT

type_of_nn: PyG
split: ${job_type}
root: ./datasets/nablaDFT/test
dataset_name: ${dataset_name}
batch_size: 32
num_workers: 12