# Dataset config for ASE nablaDFT
_target_: nablaDFT.dataset.NablaDFT

type_of_nn: ASE
datapath: ./datasets/nablaDFT/forces/train
dataset_name: ${dataset_name}
data_workdir: ./logs
train_ratio: 0.9
val_ratio: 0.1
batch_size: 32
num_workers: 8
split_file: ${.data_workdir}/split.npz

