# Dataset config for torch geometric nablaDFT
_target_: nablaDFT.dataset.get_PyG_nablaDFT_test_dataset

root: ../datasets/nablaDFT/forces/test
dataset_name: ${dataset_name}
batch_size: 512
num_workers: 12