# Dataset config for ASE nablaDFT
_target_: nablaDFT.dataset.ASENablaDFT

split: ${job_type}
root: ${root}
dataset_name: ${dataset_name}
train_ratio: 0.0
val_ratio: 0.0
test_ratio: 1.0
batch_size: ${batch_size}
num_workers: ${num_workers}
# define split strategy
splitting:
  _target_: nablaDFT.dataset.split.TestSplit

test_transforms:
  - _target_: schnetpack.transform.ASENeighborList
    cutoff: ${cutoff}
  - _target_: schnetpack.transform.CastTo32
