# Dataset config for ASE nablaDFT
_target_: nablaDFT.dataset.NablaDFT

type_of_nn: ASE
datapath: ./datasets/nablaDFT/train
dataset_name: ${dataset_name}
data_workdir: ./logs
train_ratio: 0.9
val_ratio: 0.1
batch_size: 32
num_workers: 8
split_file: ${.data_workdir}/${.dataset_name}_split.npz

train_transforms:
  - _target_: schnetpack.transform.ASENeighborList
    cutoff: 5
  - _target_: schnetpack.transform.RemoveOffsets
    property: "energy"
    remove_mean: True
    remove_atomrefs: False
  - _target_: schnetpack.transform.CastTo32
val_transforms: ${.train_transforms}