# Global variables
name: ESCN-OC-fluoro
dataset_name: rdkit_xtb
max_steps: 1000000
warmup_steps: 0
job_type: train
pretrained: null # name of pretrained split or 'null'
ckpt_path: null # path to checkpoint for training resume or test run

# Datamodule parameters
root: ./datasets/fluoro/${.job_type}
batch_size: 8
num_workers: 8

# Devices
devices: [0]

# Trainer parameters
gradient_clip_algorithm: null
gradient_clip_val: null

# configs
defaults:
  - _self_
  - datamodule: fluoro_pyg.yaml  # dataset config
  - model: escn-oc_noforces.yaml  # model config
  - callbacks: default.yaml  # pl callbacks config
  - loggers: wandb.yaml  # pl loggers config
  - trainer: train.yaml  # trainer config

# need this to set working dir as current dir
hydra:
  output_subdir: null
  run:
    dir: .
original_work_dir: ${hydra:runtime.cwd}

seed: 23
