# Global variables
name: Fluoro-PaiNN-OC-3l-bs512-pat10_rdkit_xtb_clear
dataset_name: rdkit_xtb_clear
max_steps: 1000001
job_type: predict
pretrained: null # name of pretrained split or 'null'
ckpt_path: checkpoints/Fluoro-PaiNN-OC-3l-bs512-pat10_rdkit_xtb_clear/Fluoro-PaiNN-OC-3l-bs512-pat10_rdkit_xtb_clear_rdkit_xtb_clear_epoch=129_val_loss=39.125912.ckpt # path to checkpoint for training resume or test run

# Datamodule parameters
root: ./datasets/fluoro/${.job_type}
batch_size: 512
num_workers: 8
output_dir: "./predictions"

# Devices
devices: [1]

# Trainer parameters
gradient_clip_algorithm: norm
gradient_clip_val: 5.0


# configs
defaults:
  - _self_
  - datamodule: fluoro_pyg.yaml  # dataset config
  - model: painn-oc_noforces.yaml  # model config
  - callbacks: default.yaml  # pl callbacks config
  - loggers: wandb.yaml  # pl loggers config
  - trainer: train.yaml  # trainer config

# need this to set working dir as current dir
hydra:
  output_subdir: null
  run:
    dir: .
original_work_dir: ${hydra:runtime.cwd}

seed: 23
