name: GemNet-OC
dataset_name: test_opt # used for output database name
job_type: optimize
pretrained: True # if True downloads checkpoint trained on the largest split
ckpt_path: null # path to checkpoint for training resume or test run

input_db: ./test_opt.db # relative path to input database
output_dir: ./traj_optimize # relative path to output database
batch_size: 1024
fmax: 1e-5 # condition for max norm of gradients
steps: 500 # number of optimization steps
device: cuda:0  # GPU-distributed not supported, specify device TODO: infer from devices
devices: [0]

defaults:
  - _self_
  - datamodule: nablaDFT_pyg.yaml
  - model: gemnet-oc.yaml
  - calculator: pyg_calculator.yaml
  - optimizer: batchwise_lbfgs.yaml

# need this to set working dir as current dir
hydra:
  output_subdir: null
  run:
    dir: .
original_work_dir: ${hydra:runtime.cwd}

seed: 23
