# Global variables
name: GemNet-OC
dataset_name: null # filename w/o extension from root directory
max_steps: 1000000
warmup_steps: 0
job_type: predict
pretrained: True # if True downloads checkpoint trained on the largest split
ckpt_path: null # path to checkpoint for training resume or test run

cutoff: 12.0

# Datamodule parameters
root: null # path to directory with dataset
batch_size: 32
num_workers: 8

# Devices
devices: [0]

# configs
defaults:
  - _self_
  - datamodule: nablaDFT_pyg_test.yaml  # dataset config
  - model: gemnet-oc.yaml  # model config
  - callbacks: default.yaml  # pl callbacks config
  - loggers: wandb.yaml  # pl loggers config
  - trainer: test.yaml  # trainer config

# need this to set working dir as current dir
hydra:
  output_subdir: null
  run:
    dir: .
original_work_dir: ${hydra:runtime.cwd}

seed: 23