name: GemNet-OC
dataset_name: test_opt # used for output database name
job_type: optimize
pretrained: True
ckpt_path: ./checkpoints/GemNet-OC/GemNet-OC_dataset_train_100k_epoch=085_val_loss=0.028551.ckpt

input_db: ./test_opt.db # relative path to input database
output_dir: ./traj_optimize # relative path to output database
batch_size: 1024
device: cuda:0  # GPU-distributed not supported, specify device

defaults:
  - _self_
  - model: gemnet-oc.yaml
  - calculator: pyg_calculator.yaml
  - optimizer: batchwise_lbfgs.yaml

# need this to set working dir as current dir
hydra:
  output_subdir: null
  run:
    dir: .
original_work_dir: ${hydra:runtime.cwd}

seed: 23