# Global variables
name: Graphormer3D  # name of run
dataset_name: dataset_test_structures  # dataset name from links/energy_databases.json
max_steps: 1000000
warmup_steps: 60000
job_type: test  # run type for wandb
ckpt_path: null  # path to ckpt with trained model

# configs
defaults:
  - _self_
  - datamodule: nablaDFT_pyg_test.yaml  # dataset config
  - model: graphormer3d-half.yaml  # model config
  - callbacks: default.yaml  # pl callbacks config
  - loggers: wandb.yaml  # pl loggers config
  - trainer: test.yaml  # trainer config

# need this to set working dir as current dir
hydra:
  output_subdir: null
  run:
    dir: .
original_work_dir: ${hydra:runtime.cwd}

seed: 23
