# Global variables
name: Graphormer3D-small
dataset_name: dataset_train_tiny
max_steps: 1000000
warmup_steps: 60000
job_type: train
pretrained: False # if True downloads checkpoint trained on the largest split
ckpt_path: null # path to checkpoint for training resume or test run

cutoff: 5.0

# Datamodule parameters
root: ./datasets/nablaDFT/${.job_type}
batch_size: 32
num_workers: 8

# Devices
devices: [0]

# Trainer parameters
gradient_clip_algorithm: norm
gradient_clip_val: 5.0

# configs
defaults:
  - _self_
  - datamodule: nablaDFT_pyg.yaml  # dataset config
  - model: graphormer3d-half.yaml  # model config
  - callbacks: default.yaml  # pl callbacks config
  - loggers: wandb.yaml  # pl loggers config
  - trainer: train.yaml  # trainer config

# need this to set working dir as current dir
hydra:
  output_subdir: null
  run:
    dir: .
original_work_dir: ${hydra:runtime.cwd}

seed: 23