# Global variables
name: PaiNN
dataset_name: dataset_train_2k
max_steps: 1000000
job_type: train
pretrained: False
ckpt_path: null # path to checkpoint for training resume or test run

# configs
defaults:
  - _self_
  - datamodule: nablaDFT_ase.yaml  # dataset config
  - model: painn.yaml  # model config
  - callbacks: callbacks_spk.yaml  # pl callbacks config
  - loggers: wandb.yaml  # pl loggers config
  - trainer: train.yaml  # trainer config

# need this to set working dir as current dir
hydra:
  output_subdir: null
  run:
    dir: .
original_work_dir: ${hydra:runtime.cwd}

seed: 23