# Global variables
name: homolumo-PaiNN-OC-3l-bs512
dataset_name: train
max_steps: 1000001
job_type: train
pretrained: null # name of pretrained split or 'null'
ckpt_path: null # path to checkpoint for training resume or test run

# Datamodule parameters
root: ./datasets/pcqm4mv2/${.job_type}
batch_size: 512
num_workers: 8

# Devices
devices: [1]

# Trainer parameters
gradient_clip_algorithm: norm
gradient_clip_val: 5.0


# configs
defaults:
  - _self_
  - datamodule: pcqm4mv2_pyg.yaml  # dataset config
  - model: painn-oc_noforces.yaml  # model config
  - callbacks: default.yaml  # pl callbacks config
  - loggers: wandb.yaml  # pl loggers config
  - trainer: train.yaml  # trainer config

# need this to set working dir as current dir
hydra:
  output_subdir: null
  run:
    dir: .
original_work_dir: ${hydra:runtime.cwd}

seed: 23
