# Global variables
name: SchNet
dataset_name: dataset_train_2k
max_steps: 1000000
warmup_steps: 0
job_type: train
ckpt_path: null # if training resume from checkpoint

# configs
defaults:
  - _self_
  - datamodule: nablaDFT_ase.yaml  # dataset config
  - model: schnet.yaml  # model config
  - callbacks: default.yaml  # pl callbacks config
  - loggers: wandb.yaml  # pl loggers config
  - trainer: train.yaml  # trainer config

# need this to set working dir as current dir
hydra:
  output_subdir: null
  run:
    dir: .
original_work_dir: ${hydra:runtime.cwd}

seed: 23